### ISSUE TITLE
[Bug] Key Combinations are not registered

### ISSUE THREAD

**Issue by aryan1113** [Prabalpsingh7115/PandaType#2]
Currently, key combinations are not logged and only single clicks are registered. 

ctrl + backspace removes the complete word, drastically improving speed when a word with multiple wrong characters is typed.
[This might be helpful](https://stackoverflow.com/questions/16006583/capturing-ctrlz-key-combination-in-javascript)

**Comment by Prabalpsingh7115** [comment]
Thanks @aryan1113 !

The issue has been fixed in the latest commit.
