### ISSUE TITLE
Repeated Words in "New Game

### ISSUE THREAD

**Issue by aryan1113** [Prabalpsingh7115/PandaType#4]
The "New Game" button does not create a new wordset for the next game.
Having the same set of words for the next try is undesirable

Here's a screengrab of the same : 

https://github.com/user-attachments/assets/0a37dff9-d61a-4c8c-8c38-e194ec3119dc

**Comment by Prabalpsingh7115** [comment]
Thanks @aryan1113 ! 

The issue has been fixed in the recent commit. Thanks for noticing and reporting the bug.
